version: '3.8'

services:
  php:
    image: php:8.2-cli
    container_name: phpunit_project
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    tty: true
    stdin_open: true
    environment:
      XDEBUG_MODE: coverage
